### PR TITLE
fix: search

### LINKED ISSUE #16: Search shows no results
When visiting a page and using the search feature the results are empty.

### Example

[Mistral Demo](https://mistral.bloggrify.com/)

image

image

## Potential Fix

Update logic error in [`server/api/search.ts`](https://github.com/bloggrify/bloggrify/blob/main/server/api/search.ts) to return pages that are not hidden.

### PR DESCRIPTION
**Pull request by IO-Fire**
## Linked Issue

Fix #16 

## Description

Updates logic in [`server/api/search.ts`](https://github.com/bloggrify/bloggrify/blob/main/server/api/search.ts) to find pages that are not labelled as hidden.

- Adds `pending` and `error` states.
- Adds cache for search results
- Ensures search results are not included in client bundled
  -  As size is prohibitive and requires activation to be used. 
- Fixes dark theme text
- Adds bodyLimit to search to cap search size.

Feedback and suggestions are welcome!

### CODE REVIEW

**Comment by IO-Fire** [comment]
Note that the search route appears to be computationally expensive. I can't think of a local SSG implementation that doesn't involve sending large text chunks to the client that may not be used in a search query.

Possible alternatives include offloading search to an external service like [Algolia](https://www.algolia.com/) and the [Algolia Nuxt module](https://nuxt.com/modules/algolia). Algolia is also the search provider for the [Nuxt Website](https://nuxt.com/) and many more.

File: server/api/search.ts [hunk 1]
```diff
@@ -3,45 +3,68 @@ import { serverQueryContent } from '#content/server'
...
+                title,
+                description,
+                keywords: body?.toc?.links.map(link => link?.text),
+                body: extractTextFromAst(body, bodyLimit) || ''
+            }
+        }
+    )
+
+    // Cache search results across client instances
+    setResponseHeader(event,'cache-control','max-age=300, must-revalidate')
```
Comment (hlassiege) [inline server/api/search.ts:45]: knowing it's something that occurs only at build time. Is it really necessary to set this header ?

File: components/AppSearch.vue [hunk 2]
```diff
@@ -25,9 +25,30 @@ const { activate, deactivate } = useFocusTrap(searchContentRef)
...
-    () => $fetch('/api/search', { parseResponse: JSON.parse })
+const SEARCH_DATA_KEY = 'search-api';
+
+// Cache results across pages
+// Note: does not cache across client instances, use Cache-Control headers or local storage instead
+const cachedResults = useNuxtData<BlogSearchResult[]>(SEARCH_DATA_KEY)
+
+function showSearch() {
+    show.value = true;
+    if(!!!cachedResults.data.value || (cachedResults.data.value.length === 0)){
```
Comment (hlassiege) [inline components/AppSearch.vue:36]: I'm not sure to understand this part.

The search route is prerendered at build time. It should create a huge json file, included in every page that use this component

Is it useful to cache the result of this API ? (it's already done once, no) ?

File: server/api/search.ts [hunk 3]
```diff
@@ -3,45 +3,68 @@ import { serverQueryContent } from '#content/server'
...
+        }
+    ]}).find()).filter(
+        (doc) => {
+            // Remove empty docs
+            return doc.body?.children.length !== 0;
+        }
     )
 
-    return docs
+    // TODO: Allow body limit customisation
```
Comment (hlassiege) [inline server/api/search.ts:26]: indeed, it could an advanced option in app.config.ts

**Review by hlassiege — COMMENTED** [review]
I like the approach. 
thanks a lot for this contribution

I have some doubt however on the caching system, knowing it's done only at build time. Could you explain a bit ?

**Comment by hlassiege** [comment]
indeed, the search system is not efficient for large blogs.
It used to work for my own blog, which is quite large for a personal blog (and apparently it's broken now ^^) but indeed, bloggrify should propose an alternative for larger blogs

algolia could be the alternative solution for large content and could be propose as an option to the current system.

File: server/api/search.ts (hunk 3 above)
Comment (IO-Fire) [reply server/api/search.ts:26]: Agreed, will want separate PR as this one is primarily fixes only.

File: server/api/search.ts (hunk 1 above)
Comment (IO-Fire) [reply server/api/search.ts:45]: While it is statically set at build time, clients don't know the content doesn't change and make a request each time. The cache header informs clients. For example web browsers may use a cached copy instead of requesting the data each time until the max-age. 

The use-case is allow separate client instances to share the cache. For example if the user opens two browser tabs within the max-age, the resource is fetched only once.

File: components/AppSearch.vue (hunk 2 above)
Comment (IO-Fire) [reply components/AppSearch.vue:36]: While the search route is prerendered at build time, it is not included in the page payload due to SSR process not fetching the information at build time on a page. 

The size of the page is kept minimal as the results are not required for page rendering until the user activates search, reducing the initial page loading time.

This is due to setting immediate to false and the execute function is only called by an action not performed in the server render.

The client instance needs to fetch the  data as it is not included in the payload. 

Instead of fetching the data each time when a user navigates between pages (CSR mode) and uses search, the useNuxtData caches the result in the client instance. The logic controls when to execute the fetch based on the initial cache contents being empty.

The result is not cached between client instances. See the search api code comments on how it could be cached across instances.

Comment (hlassiege) [reply components/AppSearch.vue:36]: ok, I understand
Thanks for your explanation !
